#include "cli/align_command.h"
#include "cli/errors.h"
#include "cli/help.h"
#include "cli/index_command.h"
#include "cli/parse.h"
#include "cli/report.h"
#include "fa_version.h"  // FA_VERSION, generated by CMake

#include <chrono>
#include <csignal>
#include <iostream>
#include <stdexcept>
#include <string>

int main(int argc, char** argv) {
    const auto start = std::chrono::steady_clock::now();
    const auto elapsed = [&] {
        return std::chrono::duration<double>(
                   std::chrono::steady_clock::now() - start)
            .count();
    };
    // Which --help a usage error points at: the subcommand once recognised.
    std::string usage_scope;
    try {
        // Safe because printf and cout are never mixed.
        std::ios_base::sync_with_stdio(false);
        // A closed downstream pipe then surfaces as EPIPE, which the output
        // writer reports, instead of a silent SIGPIPE exit.
        std::signal(SIGPIPE, SIG_IGN);
        // A bare `flashalign` prints help to stderr and exits 2; --help prints
        // it to stdout and exits 0.
        if (argc < 2) {
            fa::cpu::cli::print_top_help(std::cerr);
            return 2;
        }
        if (std::string(argv[1]) == "--help") {
            fa::cpu::cli::print_top_help(std::cout);
            return 0;
        }
        const std::string command = argv[1];
        // -V/--version are top-level spellings of `version`, outside the option
        // registry like --help.
        if (command == "version" || command == "-V" || command == "--version") {
            std::cout << "flashalign " FA_VERSION "\n";
            return 0;
        }
        // A command with no arguments prints its help to stderr and exits 2.
        if (command == "align") {
            if (argc == 2) {
                fa::cpu::cli::print_align_help(std::cerr);
                return 2;
            }
            usage_scope = "align ";
            fa::cpu::cli::AlignOptions opt = fa::cpu::cli::parse_align_args(argc, argv, 2);
            const int rc = fa::cpu::cli::run_align(opt);
            // --show-config maps nothing, so it gets no footer.
            if (!opt.quiet && !opt.show_config)
                fa::cpu::cli::write_run_footer(argc, argv, elapsed());
            return rc;
        }
        if (command == "index") {
            if (argc == 2) {
                fa::cpu::cli::print_index_help(std::cerr);
                return 2;
            }
            usage_scope = "index ";
            fa::cpu::cli::IndexOptions opt = fa::cpu::cli::parse_index_args(argc, argv, 2);
            const int rc = fa::cpu::cli::run_index(opt);
            if (!opt.quiet)
                fa::cpu::cli::write_run_footer(argc, argv, elapsed());
            return rc;
        }
        throw fa::cpu::cli::UsageError("unknown command: " + command);
    } catch (const fa::cpu::cli::UsageError& e) {
        std::cerr << "flashalign: error: " << e.what() << "\n"
                  << "run 'flashalign " << usage_scope << "--help' for usage\n";
        return 2;
    } catch (const std::exception& e) {
        std::cerr << "flashalign: error: " << e.what() << "\n";
        return 1;
    }
}
